%RUN_ALL Run all verification suites and report every failure.

test_directory = fileparts(mfilename('fullpath'));
addpath(fileparts(test_directory), test_directory);

test_names = { ...
    'test_gauss_legendre', ...
    'test_incident_plane_wave', ...
    'test_sph_coords', ...
    'test_solution_validation', ...
    'test_unit_scaling', ...
    'test_special_functions', ...
    'test_coords_vecwave', ...
    'test_sphere_mie', ...
    'test_scalar_approximation', ...
    'test_physics', ...
    'test_barton2001'};
failed_names = {};

for test_index = 1:numel(test_names)
    test_name = test_names{test_index};
    started = tic;
    try
        feval(test_name);
        fprintf('[PASS] %-24s %.3f s\n', test_name, toc(started));
    catch exception
        failed_names{end + 1} = test_name; %#ok<SAGROW>
        fprintf(2, '[FAIL] %-24s %.3f s\n%s\n', test_name, ...
            toc(started), getReport(exception, 'extended', ...
            'hyperlinks', 'off'));
    end
end

if ~isempty(failed_names)
    error('run_all:FailedTests', '%d of %d tests failed: %s.', ...
        numel(failed_names), numel(test_names), strjoin(failed_names, ', '));
end
fprintf('All %d test suites passed.\n', numel(test_names));
